samples: "/home/ccrutti/Bureau/circRNA/samples.tsv"
annotations:
  sus_scrofa: "/home/ccrutti/Bureau/circRNA/testdata/annotation.bed"
wdir: "results"
report: "report"
min_ccr: 5
tolerance: 0
min_size: 55
